### ISSUE TITLE
Create tests that lint styles

### ISSUE THREAD

**Issue by CodeTheory** [wulkano/molten#4]
We need to define the rules we want to enforce within molten. You can see the rules here: https://github.com/stylelint/stylelint/blob/master/docs/user-guide/rules.md

I propose we use:
[`string-quotes`](https://github.com/stylelint/stylelint/blob/master/src/rules/string-quotes/README.md): single quotes
[`color-hex-case`](https://github.com/stylelint/stylelint/blob/master/src/rules/color-hex-case/README.md): lowercase hex values
[`number-no-trailer-zeros`](https://github.com/stylelint/stylelint/blob/master/src/rules/number-no-trailing-zeros/README.md): disallow trailing zeroes
[`number-zero-length-no-unit`](https://github.com/stylelint/stylelint/blob/master/src/rules/number-zero-length-no-unit/README.md): Disallow units following zeroes
[`value-no-vendor-prefix`](https://github.com/stylelint/stylelint/blob/master/src/rules/number-zero-length-no-unit/README.md): Don't allow vendor prefixes because of the use of autoprefixer
[`property-no-vendor-prefix`](https://github.com/stylelint/stylelint/blob/master/src/rules/property-no-vendor-prefix/README.md): Disallow vendor prefixes on properties for the same reason as above
[`declaration-no-important`](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-no-important/README.md): Nothing should be `!important` in a reset
[`declaration-colon-space-after`](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-colon-space-after/README.md): Always have spaces after colons
[`declaration-block-semicolon-newline-after`](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-semicolon-newline-after/README.md): Always have newlines after semicolons
[`declaration-block-single-line-max-declarations`](https://github.com/stylelint/stylelint/blob/master/src/rules/declaration-block-single-line-max-declarations/README.md): Only a single declaration for a single line
[`block-closing-brace-newline-after`](https://github.com/stylelint/stylelint/blob/master/src/rules/block-closing-brace-newline-after/README.md): There should always be a newline after a closing brace
[`block-closing-brace-space-before`](https://github.com/stylelint/stylelint/blob/master/src/rules/block-closing-brace-space-before/README.md): Always have a space before a closing brace for single line declarations
[`block-no-empty`](https://github.com/stylelint/stylelint/blob/master/src/rules/block-no-empty/README.md): No empty blocks
[`selector-no-vendor-prefix`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-no-vendor-prefix/README.md): No vendor prefixes due to autoprefixer
[`selector-pseudo-element-colon-notation`](https://github.com/stylelint/stylelint/blob/master/src/rules/selector-pseudo-element-colon-notation/README.md): Double or single colons not either/both
[`rule-no-duplicate-properties`](https://github.com/stylelint/stylelint/blob/master/src/rules/rule-no-duplicate-properties/README.md): Fallbacks should be through functions so disallow duplicate properties
[`rule-trailing-semicolon`](https://github.com/stylelint/stylelint/blob/master/src/rules/rule-trailing-semicolon/README.md): Require final semicolons
[`media-feature-colon-space-after`](https://github.com/stylelint/stylelint/blob/master/src/rules/media-feature-colon-space-after/README.md): Require a space after a colon in a media query
[`media-feature-name-no-vendor-prefix`](https://github.com/stylelint/stylelint/blob/master/src/rules/media-feature-name-no-vendor-prefix/README.md): Again with vendor prefixes
[`media-feature-range-operator-space-after `](https://github.com/stylelint/stylelint/blob/master/src/rules/media-feature-range-operator-space-after/README.md): Space after range operators in media queries
[`comment-whitespace-inside`](https://github.com/stylelint/stylelint/blob/master/src/rules/comment-whitespace-inside/README.md): Require whitespace in comments for readability
[`indentation`](https://github.com/stylelint/stylelint/blob/master/src/rules/indentation/README.md): Require indentation

/cc @doot0

**Comment by doot0** [comment]
Seems reasonable enough. :+1:

**Comment by CodeTheory** [comment]
This issue is addressed in #5.
